// <auto-generated />
using System;
using Bet.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bet.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bet.Domain.GameManagement.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayTeamGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("away_team_goals");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<int>("HomeTeamGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("home_team_goals");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("status");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_games_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_games_home_team_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Bet.Domain.PredictionManagement.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayTeamGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("away_team_goals");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("HomeTeamGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("home_team_goals");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_predictions");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_predictions_game_id");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("Bet.Domain.TeamManagement.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Logo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Bet.Domain.GameManagement.Game", b =>
                {
                    b.HasOne("Bet.Domain.TeamManagement.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_teams_away_team_id");

                    b.HasOne("Bet.Domain.TeamManagement.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_teams_home_team_id");

                    b.OwnsOne("Bet.Domain.Shared.ValueObjects.Tournament", "Tournament", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("GameId")
                                .HasName("pk_games");

                            b1.ToTable("games");

                            b1.ToJson("tournament");

                            b1.WithOwner()
                                .HasForeignKey("GameId")
                                .HasConstraintName("fk_games_games_game_id");
                        });

                    b.Navigation("Tournament")
                        .IsRequired();
                });

            modelBuilder.Entity("Bet.Domain.PredictionManagement.Prediction", b =>
                {
                    b.HasOne("Bet.Domain.GameManagement.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_predictions_games_game_id");
                });

            modelBuilder.Entity("Bet.Domain.TeamManagement.Team", b =>
                {
                    b.OwnsOne("Bet.Domain.Shared.ValueObjects.TournamentList", "TournamentList", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("TeamId");

                            b1.ToTable("teams");

                            b1.ToJson("tournaments");

                            b1.WithOwner()
                                .HasForeignKey("TeamId")
                                .HasConstraintName("fk_teams_teams_id");

                            b1.OwnsMany("Bet.Domain.Shared.ValueObjects.Tournament", "Tournaments", b2 =>
                                {
                                    b2.Property<Guid>("TournamentListTeamId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("TournamentListTeamId", "Id")
                                        .HasName("pk_teams");

                                    b2.ToTable("teams");

                                    b2.WithOwner()
                                        .HasForeignKey("TournamentListTeamId")
                                        .HasConstraintName("fk_teams_teams_tournament_list_team_id");
                                });

                            b1.Navigation("Tournaments");
                        });

                    b.Navigation("TournamentList");
                });
#pragma warning restore 612, 618
        }
    }
}
